// Generated by scripts/build-hero-map.mjs — do not edit by hand.
import type { Neighborhood } from "@/lib/types";

/** Where the city camera lands (SVG user units): the seeded neighborhoods + the shrine. */
export const MASHHAD_BOX = { x: 1303.46, y: 341.50, w: 14.76, h: 10.50 } as const;

export const HOOD_POINTS: { fa: Neighborhood; x: number; y: number }[] = [{"fa":"الهیه","x":1305.87,"y":342.95},{"fa":"قاسم‌آباد","x":1307.72,"y":344.95},{"fa":"وکیل‌آباد","x":1306.2,"y":346.55},{"fa":"هاشمیه","x":1307.64,"y":348.95},{"fa":"سجاد","x":1311.68,"y":348.15},{"fa":"احمدآباد","x":1313.62,"y":350.35}];

export const SHRINE = {"fa":"حرم","x":1317.01,"y":351.23} as const;
